### ISSUE TITLE
A Major Glitch with v2.1 wallet 

### ISSUE THREAD

**Issue by 360view** [bumbacoin/xgox#2]
I upgraded to v2.1 wallet as instructed and after sync is done, discovered that my wallet balance was wiped out to zero.  I believe there is a glitch.  Here's what happened.

1. On 11/10 (Before upgrading), I sent 4010 to a cryptopia wallet GczbZB8jMvxb9fJzdpdsytnzPZ9aacCBJG Transaction ID: de545bc0c3f13e530e55a2a11b38ca58499f80b64f78133f0386a3c9f85ada3d  
The remaining balance was 13154.7801787 after the transfer.

2. On 11/11, I Backed up the wallet & upgraded the wallet to v2.1 as per instruction

3. After sync is done, I noticed the balance of wallet was 0.  Upon checking the transaction record, I noticed two transactions with the same Transaction ID de545bc0c3f13e530e55a2a11b38ca58499f80b64f78133f0386a3c9f85ada3d as follows:

- 11/10: GRvxc8coQimJRWKgKZsjUiv1saSzurTa7a -13154.7801787
- 11/10: GczbZB8jMvxb9fJzdpdsytnzPZ9aacCBJG -4010.00

See here: http://173.254.204.74:12313/tx/de545bc0c3f13e530e55a2a11b38ca58499f80b64f78133f0386a3c9f85ada3d

Can you correct this error and restore the balance back?
Thank you very much.

**Comment by bumbacoin** [comment]
this will not be a code problem.
when you sent the coins to cryptopia, the wallet sent your change to a new address, 
you had 17164 coins, you sent 4010 to cryptopia, the remainder/change of 13154 coins went to a new address in your wallet.
those funds are still there at 
http://173.254.204.74:12313/address/GRvxc8coQimJRWKgKZsjUiv1saSzurTa7a

either your back up wallet does not contain that address, or the wallet just needs repairing
please go into your debug/console and enter
`repairwallet`

if still problems please come into discord channel for assistance.
thanks
