### ISSUE TITLE
Wallet Issues

### ISSUE THREAD

**Issue by cody5005** [bumbacoin/xgox#4]
I had the old wallet, I originally bought approx 55k xgox coins and put them in to stake, this was about 10 days ago, it said I would get my first stake in approx 3 days, It said that for about 3 days, then went to 2 days, then said that up until now 7 days later. I downloaded the new wallet and been using it for 2 and a half days or so now as I was told this would fix that issue, it didnt. It said 2 days still when I got the new wallet, and now 2 and a half days later, it says 2 days still. I got about 430k weight currently, started with 50k, 0 stakes, and doesnt look like it will ever stake honestly. Cant find any help from google or YouTube or my friends who stake

**Comment by hsvict** [comment]
some problem and wallet now syncing

**Comment by cody5005** [comment]
Still cant get wallet to sync except its a new issue, I got the most
updated wallet that came out like 2 or 3 days ago. I cant figure it out
because no youtube videos on it or google articles either

**Comment by bumbacoin** [comment]
please come to xgox discord for assistance
 https://discord.gg/s4HC8Zb

**Comment by esquire042** [comment]
Check whether your wallet block height tally with xgox block explore, if it is correct then you have nothing to worry about. The longer  wait the higher reward you receive. At time I get my reward after 13 days but it will be higher than that of a week
