### ISSUE TITLE
last version 2222 not working on Mac OS High Sierra

### ISSUE THREAD

**Issue by sciack76** [bumbacoin/xgox#7]
It is not even starting.

<img width="434" alt="screen shot 2561-02-08 at 21 30 21" src="https://user-images.githubusercontent.com/30981989/35978179-9aab3e72-0d17-11e8-8fee-0b5e8aeb5bb8.png">

**Comment by bumbacoin** [comment]
i'm sorry, my mistake, am uploading a working version now.
