### ISSUE TITLE
Seed node?

### ISSUE THREAD

**Issue by xlp0rk0lx** [bumbacoin/xgox#9]
Hi guys, i need to sync the chain in order to a legal issue. Does someone have a copy of the chain or a seed node? 

I need to sync at least until 22/06/2018.

Thank you in advice

**Comment by xlp0rk0lx** [comment]
Found these one.
Add to the xgox.conf file

addnode=101.176.118.103 
addnode=109.235.67.6 
addnode=118.208.27.160:55752
addnode=120.151.89.179 
addnode=124.149.60.252 
addnode=146.70.59.27:60382
addnode=173.254.204.74 
addnode=176.9.164.234:51824
addnode=185.144.62.253:23185
addnode=185.144.62.253:58316
addnode=185.156.123.43:53102
addnode=185.49.242.1:4509
addnode=188.79.102.49:63743
addnode=192.99.175.119:23185
addnode=198.23.219.66 
addnode=204.44.93.133 
addnode=222.14.36.191 
addnode=23.152.0.160 
addnode=37.221.194.168:53084
addnode=51.195.145.167:57767
addnode=59.168.56.132 
addnode=61.164.253.37 
addnode=64.180.219.215 
addnode=70.24.33.136:23185
addnode=70.31.181.163:62184
addnode=72.82.239.210:36872
addnode=73.244.171.230 
addnode=78.26.141.236:23185
addnode=81.224.91.74
addnode=82.169.168.31:23185
addnode=83.82.92.130 
addnode=84.28.37.230 
addnode=89.176.78.214:56378
addnode=93.82.77.112:50206
addnode=94.134.177.198:10045
addnode=95.217.78.81:23185
addnode=99.254.88.199

**Comment by bumbacoin** [comment]
i found this, uploaded july 17 2018,
block 320572

https://drive.google.com/file/d/1jzn-Np6W_QMD86Kya10Yz4BdBhJ0PmEa/view?usp=sharing
